import { Crop } from "@/types/crop-water/types";

export const crops: Crop[] = [
    {
        id: "maize",
        name: "Maize",
        scientificName: "Zea mays",
        water: { min: 500, max: 800, demand: "High" },
        temperature: { min: 18, max: 30 },
        ph: { min: 5.5, max: 7.5 },
        moisture: { min: 60, max: 80 },
        rainfall: { min: 500, max: 800 },
        droughtTolerance: 45,
        stages: [
            { name: "Germination", demand: 35 },
            { name: "Vegetative", demand: 65 },
            { name: "Flowering", demand: 100 },
            { name: "Grain Fill", demand: 80 },
            { name: "Maturity", demand: 30 },
        ],
        criticalStage: "Flowering",
        description:
            "Maize needs consistent moisture throughout its growth cycle. Water stress around flowering can significantly affect grain formation.",
    },
    {
        id: "sorghum",
        name: "Sorghum",
        scientificName: "Sorghum bicolor",
        water: { min: 350, max: 650, demand: "Medium" },
        temperature: { min: 25, max: 32 },
        ph: { min: 5.5, max: 8 },
        moisture: { min: 45, max: 70 },
        rainfall: { min: 350, max: 650 },
        droughtTolerance: 85,
        stages: [
            { name: "Germination", demand: 30 },
            { name: "Vegetative", demand: 60 },
            { name: "Flowering", demand: 90 },
            { name: "Grain Fill", demand: 65 },
            { name: "Maturity", demand: 25 },
        ],
        criticalStage: "Flowering",
        description:
            "Sorghum is relatively drought tolerant and can perform well where water availability is limited.",
    },
    {
        id: "beans",
        name: "Common Beans",
        scientificName: "Phaseolus vulgaris",
        water: { min: 300, max: 500, demand: "Medium" },
        temperature: { min: 18, max: 30 },
        ph: { min: 6, max: 7 },
        moisture: { min: 50, max: 70 },
        rainfall: { min: 300, max: 500 },
        droughtTolerance: 50,
        stages: [
            { name: "Germination", demand: 45 },
            { name: "Vegetative", demand: 65 },
            { name: "Flowering", demand: 100 },
            { name: "Pod Fill", demand: 85 },
            { name: "Maturity", demand: 35 },
        ],
        criticalStage: "Flowering",
        description:
            "Beans need regular moisture but can be sensitive to excessive water and poor drainage.",
    },
    {
        id: "tomato",
        name: "Tomato",
        scientificName: "Solanum lycopersicum",
        water: { min: 400, max: 600, demand: "High" },
        temperature: { min: 18, max: 27 },
        ph: { min: 6, max: 6.8 },
        moisture: { min: 60, max: 80 },
        rainfall: { min: 400, max: 600 },
        droughtTolerance: 35,
        stages: [
            { name: "Seedling", demand: 45 },
            { name: "Vegetative", demand: 70 },
            { name: "Flowering", demand: 90 },
            { name: "Fruit Set", demand: 100 },
            { name: "Maturity", demand: 75 },
        ],
        criticalStage: "Fruit Set",
        description:
            "Tomatoes benefit from consistent soil moisture. Large fluctuations can affect fruit quality and development.",
    },
    {
        id: "groundnut",
        name: "Groundnut",
        scientificName: "Arachis hypogaea",
        water: { min: 450, max: 700, demand: "Medium" },
        temperature: { min: 22, max: 30 },
        ph: { min: 5.5, max: 7 },
        moisture: { min: 45, max: 65 },
        rainfall: { min: 450, max: 700 },
        droughtTolerance: 65,
        stages: [
            { name: "Germination", demand: 35 },
            { name: "Vegetative", demand: 60 },
            { name: "Flowering", demand: 85 },
            { name: "Pod Formation", demand: 100 },
            { name: "Maturity", demand: 30 },
        ],
        criticalStage: "Pod Formation",
        description:
            "Groundnuts require adequate moisture during flowering and pod formation but benefit from drier conditions near harvest.",
    },
    {
        id: "rice",
        name: "Rice",
        scientificName: "Oryza sativa",
        water: { min: 1000, max: 1500, demand: "Very High" },
        temperature: { min: 20, max: 35 },
        ph: { min: 5.5, max: 6.5 },
        moisture: { min: 75, max: 95 },
        rainfall: { min: 1000, max: 1500 },
        droughtTolerance: 20,
        stages: [
            { name: "Establishment", demand: 70 },
            { name: "Vegetative", demand: 85 },
            { name: "Flowering", demand: 100 },
            { name: "Grain Fill", demand: 90 },
            { name: "Maturity", demand: 45 },
        ],
        criticalStage: "Flowering",
        description:
            "Rice has a high water requirement compared with many common field crops, particularly during reproductive growth.",
    },
]